## A collection of useful two letter aliases
## Add the aliases to ~/.bashrc or ~/.bash_profile and restart shell. 
alias ll="ls -alht"
alias ga="git add *"
alias gc="git commit -a"
alias gp="git push"
alias gs="git status"
alias gl="git pull"
alias gb="git branch -a"
alias bu="brew upgrade"
alias gk="git checkout"
alias bc="brew cleanup"
alias bp="brew prune"
alias sr="sbt run"
alias sc="sbt compile"
alias gn="git clone"
alias gt="git stash"
alias gtp="git stash pop"
alias bi="brew install"

